version: "2"         # required to adjust maintainability checks
checks:
  similar-code:
    config:
      threshold: 50
exclude_patterns: ["config/", "db/", "dist/", "features/", "**/node_modules/", "script/",
                    "**/spec/", "**/test/", "**/tests/", "Tests/", "**/vendor/", "**/*_test.go",
                    "**/*.d.ts", 'src/core/main/migrations']
